import { FaStar } from "react-icons/fa";
import { PiBathtubFill } from "react-icons/pi";
import { FaCar } from "react-icons/fa";
import { TbRuler2 } from "react-icons/tb";
import { IoCallOutline } from "react-icons/io5";
import { FaWhatsapp } from "react-icons/fa";
import { CiLocationOn } from "react-icons/ci";
import { FaBed } from "react-icons/fa";
import { GiWallet } from "react-icons/gi";

import {
  logo,
  feedbackImg,
  icon1,
  icon2,
  icon3,
  icon4,
  firsttown,
  secondtown,
  thirdtown,
  fourthtown,
  fifthtown,
  villa,
  cat,
  house,
  sofa,
  hall,
  hall1,
  footerImg,
} from "../../assets/Imges";

export const navLinks = [
  { title: "Home" },
  { title: "About" },
  {
    title: "Properties",
    dropdown: [
      { title: "All Properties", icon: icon1 },
      { title: "Trending Listings", icon: icon2 },
      { title: "Exclusive Properties", icon: icon3 },
      { title: "Explore Cities", icon: icon4 },
    ],
  },
  { title: "Contact" },
];

export const navAssets = {
  logo,
  feedbackImg,
};

export const latestProject = [
  {
    img: firsttown,
    town: "Town House",
    properties: "2 Properties",
  },
  {
    img: secondtown,
    town: "Town House",
    properties: "2 Properties",
  },
  {
    img: thirdtown,
    town: "Town House",
    properties: "2 Properties",
  },
  {
    img: fourthtown,
    town: "Town House",
    properties: "2 Properties",
  },
  {
    img: fifthtown,
    town: "Town House",
    properties: "2 Properties",
  },
];

export const trendingListings = [
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Luxury Urban Loft",
    rateing: "4.8",
    starIcon: FaStar,
    location: "Loger",
    bathroomIcon: PiBathtubFill,
    bathroom: "1",
    carIcon: FaCar,
    car: "2",
    rulerIcon: TbRuler2,
    size: "1.5m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Beachfront Villa",
    rateing: "4.9",
    starIcon: FaStar,
    location: "Kandahar",
    bathroomIcon: PiBathtubFill,
    bathroom: "3",
    carIcon: FaCar,
    car: "5",
    rulerIcon: TbRuler2,
    size: "5m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: villa,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
];

export const exclusiveProperties = [
  {
    img: villa,
    title: "Villa One Hyde Park",
    locationicon: CiLocationOn,
    location: "125 Downtown St",
    bedicon: FaBed,
    bed: "4",
    bathroomIcon: PiBathtubFill,
    bathroom: "3",
    walleticon: GiWallet,
    wallet: "555",
  },
  {
    img: fourthtown,
    title: "Luxury Apartment",
    locationicon: CiLocationOn,
    location: "125 Downtown St",
    bedicon: FaBed,
    bed: "4",
    bathroomIcon: PiBathtubFill,
    bathroom: "3",
    walleticon: GiWallet,
    wallet: "650",
  },
  {
    img: fifthtown,
    title: "Modern House",
    locationicon: CiLocationOn,
    location: "125 Downtown St",
    bedicon: FaBed,
    bed: "1",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    walleticon: GiWallet,
    wallet: "750",
  },
];

export const PropertiesforSale_Rent = [
  {
    img: hall,
    title: "Modern Cozy Cottage",
    rateing: "4.5",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "2",
    carIcon: FaCar,
    car: "3",
    rulerIcon: TbRuler2,
    size: "2m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: house,
    title: "Modern Cozy Cottage",
    rateing: "4.8",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "3",
    carIcon: FaCar,
    car: "4",
    rulerIcon: TbRuler2,
    size: "5m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
  {
    img: sofa,
    title: "Modern Cozy Cottage",
    rateing: "4.9",
    starIcon: FaStar,
    location: "Kabul",
    bathroomIcon: PiBathtubFill,
    bathroom: "4",
    carIcon: FaCar,
    car: "6",
    rulerIcon: TbRuler2,
    size: "7m",
    phoneIcon: IoCallOutline,
    call: "Call",
    whatsappIcon: FaWhatsapp,
    whatsapp: "WhatsApp",
  },
];
